# Generated by Django 4.2.1 on 2023-05-18 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('all_points', models.TextField(blank=True)),
                ('closest_points', models.TextField(blank=True)),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
