# Generated by Django 4.2.1 on 2023-05-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='coordinates',
            field=models.CharField(max_length=200),
        ),
    ]
