# Generated by Django 4.2.1 on 2023-05-18 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('koaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
