# Generated by Django 4.2.1 on 2023-05-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koaapi', '0002_alter_point_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='coordinates',
        ),
    ]
