# Generated by Django 4.2.1 on 2023-05-18 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('koaapi', '0003_remove_point_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
